name: comment-on-pr
on: [push, pull_request]
jobs:
  example:
    name: comment
    runs-on: ubuntu-latest
    steps:
      - name: comment on PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          msg: "Check out this message!"
